### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by n-hor** [mrTimofey/vue-admin#2]
Здравствуйте, при запуске admin:build - получаю такую ошибку 
Module parse failed: Unexpected token (48:44)
You may need an appropriate loader to handle this file type.
| });
|
| const root = new Vue({ store, router, i18n, ...app });
| root.$mount(document.body.querySelector('[data-root-element]'));
|

**Comment by mrTimofey** [comment]
Какая версия пакета стоит?
vue-admin-front.config.js в корне вашего проекта не создавали? Что в нём, если создавали?
Какая версия node/npm?
Команда admin:build такая, как в readme?

**Comment by mrTimofey** [comment]
Закрываю из-за неактивности.
